# Generated by Django 3.1.7 on 2021-04-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emarket', '0002_auto_20210407_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
